creator: dennyrwa
lang: id
locale: id_ID
themecolor: e73e4a
company: klikada.com
url: https://qr.klikada.com
siteurl: https://qr.klikada.com
icon: /favicon.ico
logo: /images/nav-logo.webp
alt-logo: Logo of qr.klikada.com
twitter: https://twitter.com/
facebook: https://business.facebook.com/
instagram: https://www.instagram.com/
youtube: 
copyright: 
whatsapp-float-desktop: 
whatsapp-float-phone: 
whatsapp-api: 
exclude: [README.md]
email: 
streetAddress: Jalan Mayjend Sungkono III Perum Kutoanyar Permai Blok A No. 1
postOfficeBoxNumber: 
addressLocality: Tulungagung
addressRegion: Jawa Timur
postalCode: 61258
addressCountry: Indonesia
telephone-kantor: 
telephone-detail-kantor: 
telephone: 628223267100
telephone-detail: +628-223-226-7100
telephone2: 
telephone-detail2: 
telephone3: 
telephone-detail3: 
fb_app_id: 
DMCA: 
place_id : 
id_pelacakan_ga: 
google-my-bussiness:
apk: 
permalink: pretty
collections:
  data-qr:
    output: true
    permalink: /:name/